name: Disk Usage Health Check

on:
  workflow_dispatch:     # Manually triggered
  schedule:
    - cron: '0 6 * * *'   # Daily at 6 AM UTC

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run disk_alert.sh
        run: |
          chmod +x disk_alert.sh
          bash disk_alert.sh

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: disk-alert-log
          path: ./logs/disk_alerts.log

